### ISSUE TITLE
"task switch not allowed from inside staged nor pure functions"

### ISSUE THREAD

**Issue by Joh11** [EnzymeAD/Enzyme.jl#1172]
(copy of [this discourse thread](https://discourse.julialang.org/t/ad-with-enzyme-jl-task-switch-not-allowed-from-inside-staged-nor-pure-functions/106944), since it was suggested to me that this is a bug in Enzyme and not an error on my side)

I am trying to use Enzyme to compute a gradient. I want to use gradient descent to find the optimal parameters to reproduce the spectrum of a family of Hamiltonians (i.e. just 2x2 hermitian matrices). Here is my MWE:

```julia
using Enzyme

function H(kfrac, Δ)
    γ = 1 + exp(-2im*π * kfrac[1]) + exp(-2im*π * kfrac[2])
    [Δ γ;
     γ' -Δ]
end

function eigvals2d(H)
    # only work for 2x2 matrices
    # @assert size(H) == (2, 2)
    # assume H is hermitian; if not UB
    a = H[1, 1]
    b = H[1, 2]
    d = H[2, 2]

    Δ = (d-a)^2 + 4abs2(b)

    (a+d)/2 .+ √Δ/2 * [1, -1]
end

function loss(Es, Δ)
    # compute eigenvalues with Δ
    kpath = [0.0  -0.00277778  -0.00555556  -0.00833333;
             0.0   0.00277778   0.00555556   0.00833333;
             0.0   0.0          0.0          0.0]
    
    # Espred = real.(hcat([eigvals2d(H(kpath[:, k], Δ)) for k in 1:4]...))
    Espred = zeros(2, 4)
    for k in 1:4
        Espred[:, k] = eigvals2d(H(kpath[:, k], Δ))
    end

    # return mean square error
    err = reshape(Es, :) - reshape(Espred, :)
    sum(err .* err) / length(err)
end

Δ = 0.5
Es = [3.0413812651491097 3.0410808004168115 3.0401795026932263 3.0386776613775344; 
    -3.0413812651491097 -3.0410808004168115 -3.0401795026932263 -3.0386776613775344]

@show loss(Es, Δ)
autodiff(ReverseWithPrimal, loss, Active, Const(Es), Active(Δ))
```

Here is the error I get:
```
task switch not allowed from inside staged nor pure functions

Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base ./task.jl:767
  [2] wait()
    @ Base ./task.jl:837
  [3] uv_write(s::Base.PipeEndpoint, p::Ptr{UInt8}, n::UInt64)
    @ Base ./stream.jl:992
  [4] unsafe_write(s::Base.PipeEndpoint, p::Ptr{UInt8}, n::UInt64)
    @ Base ./stream.jl:1064
  [5] unsafe_write
    @ ./io.jl:362 [inlined]
  [6] write
    @ ./strings/io.jl:244 [inlined]
  [7] print
    @ ./strings/io.jl:246 [inlined]
  [8] print(::IJulia.IJuliaStdio{Base.PipeEndpoint}, ::String, ::String, ::Vararg{String})
    @ Base ./strings/io.jl:46
  [9] println(::IJulia.IJuliaStdio{Base.PipeEndpoint}, ::String, ::Vararg{String})
    @ Base ./strings/io.jl:75
 [10] println(xs::String)
    @ Base ./coreio.jl:4
 [11] nodecayed_phis!(mod::LLVM.Module)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler/optimize.jl:205
 [12] optimize!
    @ ~/.julia/packages/Enzyme/rbuCz/src/compiler/optimize.jl:1137 [inlined]
 [13] codegen(output::Symbol, job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}; libraries::Bool, deferred_codegen::Bool, optimize::Bool, toplevel::Bool, strip::Bool, validate::Bool, only_entry::Bool, parent_job::Nothing)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9262
 [14] _thunk(job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}, postopt::Bool) (repeats 2 times)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9830
 [15] cached_compilation
    @ ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9864 [inlined]
 [16] (::Enzyme.Compiler.var"#474#475"{DataType, UnionAll, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})(ctx::LLVM.Context)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9921
 [17] JuliaContext(f::Enzyme.Compiler.var"#474#475"{DataType, UnionAll, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/kwkKA/src/driver.jl:58
 [18] #s289#473
    @ ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9882 [inlined]
 [19] var"#s289#473"(FA::Any, A::Any, TT::Any, Mode::Any, ModifiedBetween::Any, width::Any, ReturnPrimal::Any, ShadowInit::Any, World::Any, ABI::Any, ::Any, #unused#::Type, #unused#::Type, #unused#::Type, tt::Any, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Any)
    @ Enzyme.Compiler ./none:0
 [20] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any})
    @ Core ./boot.jl:580
 [21] autodiff(::ReverseMode{true, FFIABI}, ::Const{typeof(loss)}, ::Type{Active}, ::Const{Matrix{Float64}}, ::Vararg{Any})
    @ Enzyme ~/.julia/packages/Enzyme/rbuCz/src/Enzyme.jl:207
 [22] autodiff(::ReverseMode{true, FFIABI}, ::typeof(loss), ::Type, ::Const{Matrix{Float64}}, ::Vararg{Any})
    @ Enzyme ~/.julia/packages/Enzyme/rbuCz/src/Enzyme.jl:222
 [23] top-level scope
    @ In[1]:44
```

The other strange thing is that the error is not the same, running from the REPL or from a JupyterLab notebook. This was the error from the notebook, and here is the one from the REPL: 
```
ERROR: AssertionError: value_type(v) == nty
Stacktrace:
  [1] nodecayed_phis!(mod::LLVM.Module)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler/optimize.jl:208
  [2] optimize!
    @ ~/.julia/packages/Enzyme/rbuCz/src/compiler/optimize.jl:1137 [inlined]
  [3] codegen(output::Symbol, job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}; libraries::Bool, deferred_codegen::Bool, optimize::Bool, toplevel::Bool, strip::Bool, validate::Bool, only_entry::Bool, parent_job::Nothing)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9262
  [4] _thunk(job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}, postopt::Bool) (repeats 2 times)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9830
  [5] cached_compilation
    @ ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9864 [inlined]
  [6] (::Enzyme.Compiler.var"#474#475"{DataType, UnionAll, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})(ctx::LLVM.Context)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9921
  [7] JuliaContext(f::Enzyme.Compiler.var"#474#475"{DataType, UnionAll, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/kwkKA/src/driver.jl:58
  [8] #s289#473
    @ ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9882 [inlined]
  [9] var"#s289#473"(FA::Any, A::Any, TT::Any, Mode::Any, ModifiedBetween::Any, width::Any, ReturnPrimal::Any, ShadowInit::Any, World::Any, ABI::Any, ::Any, #unused#::Type, #unused#::Type, #unused#::Type, tt::Any, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Any)
    @ Enzyme.Compiler ./none:0
 [10] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any})
    @ Core ./boot.jl:580
 [11] autodiff(::ReverseMode{true, FFIABI}, ::Const{typeof(loss)}, ::Type{Active}, ::Const{Matrix{Float64}}, ::Vararg{Any})
    @ Enzyme ~/.julia/packages/Enzyme/rbuCz/src/Enzyme.jl:207
 [12] autodiff(::ReverseMode{true, FFIABI}, ::typeof(loss), ::Type, ::Const{Matrix{Float64}}, ::Vararg{Any})
    @ Enzyme ~/.julia/packages/Enzyme/rbuCz/src/Enzyme.jl:222
 [13] top-level scope
    @ REPL[9]:1
```

Version info:
```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver1)
```

A big amount of assembly is dumped to stdout. I have attached these in two files. 

[output_repl.txt](https://github.com/EnzymeAD/Enzyme.jl/files/13514665/output_repl.txt)
[output_notebook.txt](https://github.com/EnzymeAD/Enzyme.jl/files/13514669/output_notebook.txt)

**Comment by wsmoses** [comment]
Can you retry on Enzyme.jl#main, I believe this should be fixed

**Comment by Joh11** [comment]
I retried in the REPL on #main, I still get an error, but a different one:
[output_repl_main.txt](https://github.com/EnzymeAD/Enzyme.jl/files/13515260/output_repl_main.txt)

```
ERROR: AssertionError: false
Stacktrace:
  [1] (::Enzyme.Compiler.var"#getparent#349"{LLVM.Function, LLVM.IntegerType, Int64, Dict{LLVM.PHIInst, LLVM.PHIInst}, Dict{LLVM.PHIInst, LLVM.PHIInst}, LLVM.PHIInst, LLVM.IRBuilder})(v::LLVM.ConstantExpr, offset::LLVM.ConstantInt, hasload::Bool)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/y7cZI/src/compiler/optimize.jl:285
  [2] (::Enzyme.Compiler.var"#getparent#349"{LLVM.Function, LLVM.IntegerType, Int64, Dict{LLVM.PHIInst, LLVM.PHIInst}, Dict{LLVM.PHIInst, LLVM.PHIInst}, LLVM.PHIInst, LLVM.IRBuilder})(v::LLVM.LoadInst, offset::LLVM.ConstantInt, hasload::Bool)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/y7cZI/src/compiler/optimize.jl:238
  [3] nodecayed_phis!(mod::LLVM.Module)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/y7cZI/src/compiler/optimize.jl:288
  [4] optimize!
    @ ~/.julia/packages/Enzyme/y7cZI/src/compiler/optimize.jl:1230 [inlined]
  [5] codegen(output::Symbol, job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}; libraries::Bool, deferred_codegen::Bool, optimize::Bool, toplevel::Bool, strip::Bool, validate::Bool, only_entry::Bool, parent_job::Nothing)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/y7cZI/src/compiler.jl:4656
  [6] _thunk(job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}, postopt::Bool) (repeats 2 times)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/y7cZI/src/compiler.jl:5272
  [7] cached_compilation
    @ ~/.julia/packages/Enzyme/y7cZI/src/compiler.jl:5306 [inlined]
  [8] (::Enzyme.Compiler.var"#483#484"{DataType, UnionAll, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})(ctx::LLVM.Context)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/y7cZI/src/compiler.jl:5372
  [9] JuliaContext(f::Enzyme.Compiler.var"#483#484"{DataType, UnionAll, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/kwkKA/src/driver.jl:58
 [10] #s1001#482
    @ ~/.julia/packages/Enzyme/y7cZI/src/compiler.jl:5324 [inlined]
 [11] var"#s1001#482"(FA::Any, A::Any, TT::Any, Mode::Any, ModifiedBetween::Any, width::Any, ReturnPrimal::Any, ShadowInit::Any, World::Any, ABI::Any, ::Any, #unused#::Type, #unused#::Type, #unused#::Type, tt::Any, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Any)
    @ Enzyme.Compiler ./none:0
 [12] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any})
    @ Core ./boot.jl:580
 [13] autodiff(::ReverseMode{true, FFIABI}, ::Const{typeof(loss)}, ::Type{Active}, ::Const{Matrix{Float64}}, ::Vararg{Any})
    @ Enzyme ~/.julia/packages/Enzyme/y7cZI/src/Enzyme.jl:209
 [14] autodiff(::ReverseMode{true, FFIABI}, ::typeof(loss), ::Type, ::Const{Matrix{Float64}}, ::Vararg{Any})
    @ Enzyme ~/.julia/packages/Enzyme/y7cZI/src/Enzyme.jl:224
 [15] top-level scope
    @ REPL[16]:1
```

**Comment by wsmoses** [comment]
oh that's on me, I made the new error message, itself error during construction. try now

**Comment by Joh11** [comment]
Here is the new error with the newest `gce` branch:
```
ERROR: Enzyme compilation failed.
Current scope: 
define internal fastcc void @julia_paynehanek_4750({ i64, [2 x double] }* noalias nocapture writeonly sret({ i64, [2 x double] }) %0, double %1) unnamed_addr #15 !dbg !594 {
top:
  %2 = call {}*** @julia.get_pgcstack()
  %3 = bitcast double %1 to i64, !dbg !595
  %4 = and i64 %3, 4503599627370495, !dbg !598
  %5 = or i64 %4, 4503599627370496, !dbg !601
  %6 = lshr i64 %3, 52, !dbg !603
  %7 = and i64 %6, 2047, !dbg !603
  %8 = add nsw i64 %7, -1075, !dbg !607
  %9 = ashr i64 %8, 6, !dbg !610
  %10 = and i64 %8, 63, !dbg !613
  %.not = icmp eq i64 %10, 0, !dbg !615
  br i1 %.not, label %L28, label %L38, !dbg !617

L28:                                              ; preds = %top
  %11 = load i64 addrspace(13)*, i64 addrspace(13)* addrspace(11)* addrspacecast (i64 addrspace(13)** inttoptr (i64 140453351514048 to i64 addrspace(13)**) to i64 addrspace(13)* addrspace(11)*), align 8, !dbg !618, !tbaa !321, !alias.scope !223, !nonnull !4
  %12 = getelementptr inbounds i64, i64 addrspace(13)* %11, i64 %9, !dbg !618
  %13 = load i64, i64 addrspace(13)* %12, align 8, !dbg !618, !tbaa !368
  %14 = add nsw i64 %9, 1, !dbg !621
  %15 = getelementptr inbounds i64, i64 addrspace(13)* %11, i64 %14, !dbg !621
  %16 = load i64, i64 addrspace(13)* %15, align 8, !dbg !621, !tbaa !368
  %17 = add nsw i64 %9, 2, !dbg !623
  %18 = getelementptr inbounds i64, i64 addrspace(13)* %11, i64 %17, !dbg !623
  %19 = load i64, i64 addrspace(13)* %18, align 8, !dbg !623, !tbaa !368
  br label %L108, !dbg !624

L38:                                              ; preds = %top
  %20 = icmp ugt i64 %7, 1074, !dbg !625
  br i1 %20, label %L41, label %L38.L51_crit_edge, !dbg !627

L38.L51_crit_edge:                                ; preds = %L38
  %.pre19 = load i64 addrspace(13)*, i64 addrspace(13)* addrspace(11)* addrspacecast (i64 addrspace(13)** inttoptr (i64 140453351514048 to i64 addrspace(13)**) to i64 addrspace(13)* addrspace(11)*), align 8, !dbg !628, !tbaa !321, !alias.scope !223
  br label %L51, !dbg !627

L41:                                              ; preds = %L38
  %21 = load i64 addrspace(13)*, i64 addrspace(13)* addrspace(11)* addrspacecast (i64 addrspace(13)** inttoptr (i64 140453351514048 to i64 addrspace(13)**) to i64 addrspace(13)* addrspace(11)*), align 8, !dbg !628, !tbaa !321, !alias.scope !223, !nonnull !4
  %22 = getelementptr inbounds i64, i64 addrspace(13)* %21, i64 %9, !dbg !628
  %23 = load i64, i64 addrspace(13)* %22, align 8, !dbg !628, !tbaa !368
  %24 = shl i64 %23, %10, !dbg !629
  br label %L51, !dbg !631

L51:                                              ; preds = %L38.L51_crit_edge, %L41
  %nodecayed..pre-phi = phi {} addrspace(10)* , !dbg !628
  %nodecayedoff..pre-phi = phi i64 , !dbg !628
  %.pre-phi = phi i64 addrspace(13)* [ %.pre19, %L38.L51_crit_edge ], [ %21, %L41 ], !dbg !628
  %value_phi5 = phi i64 [ 0, %L38.L51_crit_edge ], [ %24, %L41 ]
  %25 = add nsw i64 %9, 1, !dbg !628
  %26 = getelementptr inbounds i64, i64 addrspace(13)* %.pre-phi, i64 %25, !dbg !628
  %27 = load i64, i64 addrspace(13)* %26, align 8, !dbg !628, !tbaa !368
  %28 = sub nuw nsw i64 64, %10, !dbg !632
  %29 = lshr i64 %27, %28, !dbg !633
  %30 = or i64 %29, %value_phi5, !dbg !635
  %31 = shl i64 %27, %10, !dbg !636
  %32 = add nsw i64 %9, 2, !dbg !639
  %33 = getelementptr inbounds i64, i64 addrspace(13)* %.pre-phi, i64 %32, !dbg !639
  %34 = load i64, i64 addrspace(13)* %33, align 8, !dbg !639, !tbaa !368
  %35 = lshr i64 %34, %28, !dbg !640
  %36 = or i64 %35, %31, !dbg !642
  %37 = shl i64 %34, %10, !dbg !643
  %38 = add nsw i64 %9, 3, !dbg !646
  %39 = getelementptr inbounds i64, i64 addrspace(13)* %.pre-phi, i64 %38, !dbg !646
  %40 = load i64, i64 addrspace(13)* %39, align 8, !dbg !646, !tbaa !368
  %41 = lshr i64 %40, %28, !dbg !647
  %42 = or i64 %41, %37, !dbg !649
  br label %L108, !dbg !649

L108:                                             ; preds = %L51, %L28
  %value_phi = phi i64 [ %19, %L28 ], [ %42, %L51 ]
  %value_phi1 = phi i64 [ %16, %L28 ], [ %36, %L51 ]
  %value_phi2 = phi i64 [ %13, %L28 ], [ %30, %L51 ]
  %43 = mul i64 %value_phi2, %5, !dbg !650
  %44 = zext i64 %43 to i128, !dbg !653
  %45 = shl nuw i128 %44, 64, !dbg !657
  %46 = zext i64 %5 to i128, !dbg !659
  %47 = zext i64 %value_phi1 to i128, !dbg !659
  %48 = mul nuw nsw i128 %47, %46, !dbg !668
  %49 = zext i64 %value_phi to i128, !dbg !669
  %50 = mul nuw nsw i128 %49, %46, !dbg !675
  %51 = lshr i128 %50, 64, !dbg !676
  %52 = add nuw nsw i128 %51, %48, !dbg !678
  %53 = add i128 %52, %45, !dbg !678
  %54 = icmp sgt i64 %3, -1, !dbg !683
  %55 = sub i128 0, %53, !dbg !692
  %56 = select i1 %54, i128 %53, i128 %55, !dbg !689
  %57 = shl i128 %56, 2, !dbg !693
  %.not13 = icmp eq i128 %57, 0, !dbg !696
  br i1 %.not13, label %L218, label %L150, !dbg !698

L150:                                             ; preds = %L108
  %58 = lshr i128 %56, 62, !dbg !701
  %59 = trunc i128 %58 to i64, !dbg !701
  %60 = and i64 %59, -9223372036854775808, !dbg !701
  %61 = call i128 @llvm.abs.i128(i128 %57, i1 false), !dbg !704
  %62 = call i128 @llvm.ctlz.i128(i128 %61, i1 false), !dbg !709, !range !712
  %63 = trunc i128 %62 to i64, !dbg !713
  %.neg = add nsw i64 %63, -102, !dbg !715
  %64 = sub nsw i64 102, %63, !dbg !715
  %65 = icmp ugt i64 %63, 102, !dbg !717
  %66 = zext i64 %64 to i128, !dbg !720
  %67 = lshr i128 %61, %66, !dbg !720
  %68 = icmp ugt i64 %64, 127, !dbg !720
  %69 = select i1 %68, i128 0, i128 %67, !dbg !720
  %70 = zext i64 %.neg to i128, !dbg !721
  %71 = shl i128 %61, %70, !dbg !721
  %72 = icmp ugt i64 %.neg, 127, !dbg !721
  %73 = select i1 %72, i128 0, i128 %71, !dbg !721
  %74 = select i1 %65, i128 %73, i128 %69, !dbg !719
  %75 = trunc i128 %74 to i64, !dbg !722
  %76 = shl i64 %75, 27, !dbg !723
  %.neg14 = mul nsw i64 %63, -4503599627370496, !dbg !725
  %77 = add nsw i64 %.neg14, 4598175219545276416, !dbg !725
  %78 = add i64 %77, %76, !dbg !728
  %79 = or i64 %78, %60, !dbg !730
  %80 = bitcast i64 %79 to double, !dbg !731
  %81 = zext i64 %76 to i128, !dbg !732
  %.neg15 = add nsw i64 %63, -75, !dbg !735
  %82 = sub nsw i64 75, %63, !dbg !735
  %83 = icmp ugt i64 %63, 75, !dbg !736
  %84 = zext i64 %82 to i128, !dbg !738
  %85 = shl i128 %81, %84, !dbg !738
  %86 = icmp ugt i64 %82, 127, !dbg !738
  %87 = select i1 %86, i128 0, i128 %85, !dbg !738
  %88 = zext i64 %.neg15 to i128, !dbg !739
  %89 = lshr i128 %81, %88, !dbg !739
  %90 = icmp ugt i64 %.neg15, 127, !dbg !739
  %91 = select i1 %90, i128 0, i128 %89, !dbg !739
  %92 = select i1 %83, i128 %91, i128 %87, !dbg !737
  %93 = sub i128 %61, %92, !dbg !735
  %.not16 = icmp eq i128 %93, 0, !dbg !740
  br i1 %.not16, label %L218, label %L196, !dbg !744

L196:                                             ; preds = %L150
  %94 = call i128 @llvm.ctlz.i128(i128 %93, i1 true), !dbg !745, !range !712
  %95 = trunc i128 %94 to i64, !dbg !747
  %.neg17 = add nsw i64 %95, -75, !dbg !748
  %96 = sub nsw i64 75, %95, !dbg !748
  %97 = icmp ugt i64 %95, 75, !dbg !750
  %98 = zext i64 %96 to i128, !dbg !752
  %99 = lshr i128 %93, %98, !dbg !752
  %100 = icmp ugt i64 %96, 127, !dbg !752
  %101 = select i1 %100, i128 0, i128 %99, !dbg !752
  %102 = zext i64 %.neg17 to i128, !dbg !753
  %103 = shl i128 %93, %102, !dbg !753
  %104 = icmp ugt i64 %.neg17, 127, !dbg !753
  %105 = select i1 %104, i128 0, i128 %103, !dbg !753
  %106 = select i1 %97, i128 %105, i128 %101, !dbg !751
  %107 = trunc i128 %106 to i64, !dbg !754
  %.neg18 = mul nsw i64 %95, -4503599627370496, !dbg !755
  %108 = add nsw i64 %.neg18, 4598175219545276416, !dbg !755
  %109 = add i64 %108, %107, !dbg !758
  %110 = or i64 %109, %60, !dbg !760
  %111 = bitcast i64 %110 to double, !dbg !761
  br label %L218, !dbg !762

L218:                                             ; preds = %L150, %L108, %L196
  %value_phi3 = phi double [ %80, %L196 ], [ 0.000000e+00, %L108 ], [ %80, %L150 ]
  %value_phi4 = phi double [ %111, %L196 ], [ 0.000000e+00, %L108 ], [ 0.000000e+00, %L150 ]
  %112 = lshr i128 %56, 125, !dbg !763
  %113 = trunc i128 %112 to i64, !dbg !766
  %114 = add nuw nsw i64 %113, 1, !dbg !767
  %115 = lshr i64 %114, 1, !dbg !768
  %116 = fadd double %value_phi3, %value_phi4, !dbg !769
  %117 = fmul double %116, 0x3FF921FB54442D18, !dbg !772
  %118 = fmul double %value_phi3, 0x3FF921FB58000000, !dbg !774
  %119 = fsub double %118, %117, !dbg !776
  %120 = fmul double %value_phi3, 0x3E4DDE973DCB3B3A, !dbg !774
  %121 = fsub double %119, %120, !dbg !778
  %122 = fmul double %value_phi4, 0x3FF921FB58000000, !dbg !774
  %123 = fadd double %122, %121, !dbg !778
  %124 = fmul double %value_phi4, 0x3E4DDE973DCB3B3A, !dbg !774
  %125 = fsub double %123, %124, !dbg !778
  %.sroa.0.0..sroa_idx = getelementptr inbounds { i64, [2 x double] }, { i64, [2 x double] }* %0, i64 0, i32 0, !dbg !779
  store i64 %115, i64* %.sroa.0.0..sroa_idx, align 8, !dbg !779, !noalias !223
  %.sroa.2.sroa.0.0..sroa.2.0..sroa_cast.sroa_idx = getelementptr inbounds { i64, [2 x double] }, { i64, [2 x double] }* %0, i64 0, i32 1, i64 0, !dbg !779
  store double %117, double* %.sroa.2.sroa.0.0..sroa.2.0..sroa_cast.sroa_idx, align 8, !dbg !779, !noalias !223
  %.sroa.2.sroa.2.0..sroa.2.0..sroa_cast.sroa_idx9 = getelementptr inbounds { i64, [2 x double] }, { i64, [2 x double] }* %0, i64 0, i32 1, i64 1, !dbg !779
  store double %125, double* %.sroa.2.sroa.2.0..sroa.2.0..sroa_cast.sroa_idx9, align 8, !dbg !779, !noalias !223
  ret void, !dbg !779
}

Could not analyze garbage collection behavior of
 v0:   %.pre19 = load i64 addrspace(13)*, i64 addrspace(13)* addrspace(11)* addrspacecast (i64 addrspace(13)** inttoptr (i64 140453351514048 to i64 addrspace(13)**) to i64 addrspace(13)* addrspace(11)*), align 8, !dbg !129, !tbaa !111, !alias.scope !116
 v: i64 addrspace(13)* addrspace(11)* addrspacecast (i64 addrspace(13)** inttoptr (i64 140453351514048 to i64 addrspace(13)**) to i64 addrspace(13)* addrspace(11)*)
 offset: i64 0
 hasload: true


Stacktrace:
 [1] getindex
   @ ./array.jl:861
 [2] paynehanek
   @ ./special/rem_pio2.jl:173
 [3] rem_pio2_kernel
   @ ./special/rem_pio2.jl:279
 [4] sincos
   @ ./special/trig.jl:185
 [5] sincos
   @ ./special/trig.jl:0
 [6] exp
   @ ./complex.jl:676
 [7] H
   @ ./REPL[4]:2
 [8] loss
   @ ./REPL[6]:10

Stacktrace:
  [1] (::Enzyme.Compiler.var"#getparent#350"{LLVM.Function, LLVM.IntegerType, Int64, Dict{LLVM.PHIInst, LLVM.PHIInst}, Dict{LLVM.PHIInst, LLVM.PHIInst}, LLVM.PHIInst, LLVM.LoadInst, LLVM.IRBuilder})(v::LLVM.ConstantExpr, offset::LLVM.ConstantInt, hasload::Bool)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/7p45s/src/compiler/optimize.jl:292
  [2] (::Enzyme.Compiler.var"#getparent#350"{LLVM.Function, LLVM.IntegerType, Int64, Dict{LLVM.PHIInst, LLVM.PHIInst}, Dict{LLVM.PHIInst, LLVM.PHIInst}, LLVM.PHIInst, LLVM.LoadInst, LLVM.IRBuilder})(v::LLVM.LoadInst, offset::LLVM.ConstantInt, hasload::Bool)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/7p45s/src/compiler/optimize.jl:239
  [3] nodecayed_phis!(mod::LLVM.Module)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/7p45s/src/compiler/optimize.jl:295
  [4] optimize!
    @ ~/.julia/packages/Enzyme/7p45s/src/compiler/optimize.jl:1237 [inlined]
  [5] codegen(output::Symbol, job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}; libraries::Bool, deferred_codegen::Bool, optimize::Bool, toplevel::Bool, strip::Bool, validate::Bool, only_entry::Bool, parent_job::Nothing)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/7p45s/src/compiler.jl:4656
  [6] _thunk(job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}, postopt::Bool) (repeats 2 times)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/7p45s/src/compiler.jl:5272
  [7] cached_compilation
    @ ~/.julia/packages/Enzyme/7p45s/src/compiler.jl:5306 [inlined]
  [8] (::Enzyme.Compiler.var"#485#486"{DataType, UnionAll, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})(ctx::LLVM.Context)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/7p45s/src/compiler.jl:5372
  [9] JuliaContext(f::Enzyme.Compiler.var"#485#486"{DataType, UnionAll, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/kwkKA/src/driver.jl:58
 [10] #s1001#484
    @ ~/.julia/packages/Enzyme/7p45s/src/compiler.jl:5324 [inlined]
 [11] var"#s1001#484"(FA::Any, A::Any, TT::Any, Mode::Any, ModifiedBetween::Any, width::Any, ReturnPrimal::Any, ShadowInit::Any, World::Any, ABI::Any, ::Any, #unused#::Type, #unused#::Type, #unused#::Type, tt::Any, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Any)
    @ Enzyme.Compiler ./none:0
 [12] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any})
    @ Core ./boot.jl:580
 [13] autodiff(::ReverseMode{true, FFIABI}, ::Const{typeof(loss)}, ::Type{Active}, ::Const{Matrix{Float64}}, ::Vararg{Any})
    @ Enzyme ~/.julia/packages/Enzyme/7p45s/src/Enzyme.jl:209
 [14] autodiff(::ReverseMode{true, FFIABI}, ::typeof(loss), ::Type, ::Const{Matrix{Float64}}, ::Vararg{Any})
    @ Enzyme ~/.julia/packages/Enzyme/7p45s/src/Enzyme.jl:224
 [15] top-level scope
    @ REPL[10]:1
```

**Comment by wsmoses** [comment]
Seems to be fixed as far as I can tell, please reopen if not!
