### ISSUE TITLE
Crash during GC

### ISSUE THREAD

**Issue by simsurace** [EnzymeAD/Enzyme.jl#1192]
Here is a MRE that sooner or later will produce a segfault on Enzyme v0.11.11:
```julia
using Enzyme

f(Y, θ) = abs2(only(Y) - only(θ.a))
g(x) = (a0 = x[1], a = x[2:2], B = x[3:3])
h(x) = sum(abs, g(x).a)
F(x) = f([1.], g(x)) + h(x)

function random_segfault()
    x = zeros(3)
    dx = zeros(3)
    @time Enzyme.autodiff(Reverse, F, Duplicated(x, dx))
    return dx
end

while true
    random_segfault()
end
```

Here is the stacktrace:
<details>

```
[359205] signal (11.1): Segmentation fault
in expression starting at REPL[9]:1
gc_try_setmark at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gc.c:1972 [inlined]
gc_mark_loop at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gc.c:2579
_jl_gc_collect at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gc.c:3407
ijl_gc_collect at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gc.c:3713
maybe_collect at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gc.c:1083 [inlined]
jl_gc_pool_alloc_inner at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gc.c:1450 [inlined]
jl_gc_pool_alloc_noinline at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gc.c:1511 [inlined]
jl_gc_alloc_ at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/julia_internal.h:460 [inlined]
jl_gc_alloc at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gc.c:3760
_new_array_ at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/array.c:134 [inlined]
_new_array at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/array.c:198 [inlined]
ijl_alloc_array_1d at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/array.c:436
unknown function (ip: 0x7fe4b579a04a)
unknown function (ip: 0x7fe4b57988c8)
macro expansion at ~/.julia/packages/Enzyme/v8XWi/src/compiler.jl:5220 [inlined]
enzyme_call at ~/.julia/packages/Enzyme/v8XWi/src/compiler.jl:4898 [inlined]
CombinedAdjointThunk at ~/.julia/packages/Enzyme/v8XWi/src/compiler.jl:4861 [inlined]
autodiff at ~/.julia/packages/Enzyme/v8XWi/src/Enzyme.jl:215 [inlined]
autodiff at ~/.julia/packages/Enzyme/v8XWi/src/Enzyme.jl:238 [inlined]
autodiff at ~/.julia/packages/Enzyme/v8XWi/src/Enzyme.jl:224 [inlined]
macro expansion at ./timing.jl:273 [inlined]
random_segfault at ./REPL[8]:4
top-level scope at ./REPL[9]:2
jl_toplevel_eval_flex at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/toplevel.c:903
jl_toplevel_eval_flex at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/toplevel.c:856
ijl_toplevel_eval_in at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/toplevel.c:971
eval at ./boot.jl:370 [inlined]
eval_user_input at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:153
repl_backend_loop at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:249
#start_repl_backend#46 at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:234
start_repl_backend at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:231
_jl_invoke at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2940
#run_repl#59 at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:379
run_repl at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:365
jfptr_run_repl_61336.clone_1 at ~/.julia/juliaup/julia-1.9.4+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2940
#1018 at ./client.jl:421
jfptr_YY.1018_34944.clone_1 at ~/.julia/juliaup/julia-1.9.4+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/julia.h:1880 [inlined]
jl_f__call_latest at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/builtins.c:774
#invokelatest#2 at ./essentials.jl:819 [inlined]
invokelatest at ./essentials.jl:816 [inlined]
run_main_repl at ./client.jl:405
exec_options at ./client.jl:322
_start at ./client.jl:522
jfptr__start_49509.clone_1 at ~/.julia/juliaup/julia-1.9.4+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/julia.h:1880 [inlined]
true_main at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/jlapi.c:573
jl_repl_entrypoint at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/src/jlapi.c:717
main at /cache/build/builder-amdci4-4/julialang/julia-release-1-dot-9/cli/loader_exe.c:59
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4010b8)
Allocations: 38126042 (Pool: 38085098; Big: 40944); GC: 35
Segmentation fault (core dumped)
```
</details>

**Comment by vchuravy** [comment]
Please post the backtrack so that one can more easily take an initial guess as well as verifying that one is working on the same issue.

**Comment by simsurace** [comment]
I added it to the OP

**Comment by vchuravy** [comment]
What is your Julia `versioninfo()`

**Comment by simsurace** [comment]
```
julia> versioninfo()
Julia Version 1.9.4
Commit 8e5136fa297 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```

**Comment by simsurace** [comment]
I reduced this from a 300LOC example that failed on both Julia 1.9.4 and 1.10.0-rc2. This one seems to work on 1.10.0-rc2, or at least it did not segfault within about a minute. A slightly larger MRE that also fails on 1.10.0-rc2 is the following one:
```julia
using Enzyme

function mydot(x::AbstractVector{T}, y::AbstractVector{T}) where T<:Real
    s = zero(T)
    for i in eachindex(x)
        s += x[i] * y[i]
    end
    return s
end

function f(Y, θ)
    return abs2(only(Y) - mydot(θ.a, zeros(4)))
end

function g(x)
    return (
        a0 = x[1],
        a = x[2:5],
        B = x[6:9]
    )
end

function h(x)
    θ = g(x)
    return sum(abs, θ.a)
end

function random_segfault(Y)
    F(x) = f(Y, g(x)) + h(x)
    x = zeros(9)
    dx = zeros(9)
    @time Enzyme.autodiff(Reverse, F, Duplicated(x, dx))
    return dx
end

while true
    model = random_segfault([1.])
end
```
It also gives a slightly different stacktrace:

<details>

```
GC error (probable corruption)
Allocations: 232976351 (Pool: 232934559; Big: 41792); GC: 331
Array{Float64, (9,)}[0, 0, 0, 0, 0, 0, 0, 0, 0]

thread 0 ptr queue:
~~~~~~~~~~ ptr queue top ~~~~~~~~~~
Array{Float64, (4,)}[0, 0, 0, 0]
==========
Array{Float64, (4,)}[0, 0, 0, 0]
==========
Array{Float64, (4,)}[0, 0, 0, 0]
==========
Array{Float64, (4,)}[0, 0, 0, 0]
==========
~~~~~~~~~~ ptr queue bottom ~~~~~~~~~~

[452519] signal (6.-6): Aborted
in expression starting at REPL[14]:1
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
gc_dump_queue_and_abort at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gc.c:1813
gc_mark_outrefs at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gc.c:2508 [inlined]
gc_mark_loop_serial_ at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gc.c:2677
gc_mark_loop_serial at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gc.c:2700
gc_mark_loop at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gc.c:2813 [inlined]
_jl_gc_collect at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gc.c:3137
ijl_gc_collect at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gc.c:3434
maybe_collect at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gc.c:935 [inlined]
jl_gc_pool_alloc_inner at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gc.c:1291 [inlined]
jl_gc_pool_alloc_noinline at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gc.c:1348 [inlined]
jl_gc_alloc_ at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/julia_internal.h:477 [inlined]
jl_gc_alloc at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gc.c:3486
_new_array_ at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/array.c:134 [inlined]
_new_array at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/array.c:198 [inlined]
ijl_alloc_array_1d at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/array.c:436
Array at ./boot.jl:477 [inlined]
Array at ./boot.jl:486 [inlined]
zeros at ./array.jl:636 [inlined]
zeros at ./array.jl:633 [inlined]
zeros at ./array.jl:631 [inlined]
f at ./REPL[10]:2
F at ./REPL[13]:2 [inlined]
F at ./REPL[13]:0 [inlined]
diffejulia_F_3629_inner_1wrap at ./REPL[13]:0
macro expansion at /home/simone_a/.julia/packages/Enzyme/v8XWi/src/compiler.jl:5220 [inlined]
enzyme_call at /home/simone_a/.julia/packages/Enzyme/v8XWi/src/compiler.jl:4898 [inlined]
CombinedAdjointThunk at /home/simone_a/.julia/packages/Enzyme/v8XWi/src/compiler.jl:4861 [inlined]
autodiff at /home/simone_a/.julia/packages/Enzyme/v8XWi/src/Enzyme.jl:215 [inlined]
autodiff at /home/simone_a/.julia/packages/Enzyme/v8XWi/src/Enzyme.jl:238 [inlined]
autodiff at /home/simone_a/.julia/packages/Enzyme/v8XWi/src/Enzyme.jl:224 [inlined]
macro expansion at ./timing.jl:279 [inlined]
random_segfault at ./REPL[13]:5
top-level scope at ./REPL[14]:2
jl_toplevel_eval_flex at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/toplevel.c:925
jl_toplevel_eval_flex at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/toplevel.c:877
ijl_toplevel_eval_in at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/toplevel.c:985
eval at ./boot.jl:385 [inlined]
eval_user_input at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:150
repl_backend_loop at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:246
#start_repl_backend#46 at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:231
start_repl_backend at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:228
_jl_invoke at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gf.c:2894 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gf.c:3076
#run_repl#59 at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:389
run_repl at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:375
jfptr_run_repl_91755.1 at /home/simone_a/.julia/juliaup/julia-1.10.0-rc2+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gf.c:2894 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gf.c:3076
#1013 at ./client.jl:432
jfptr_YY.1013_82750.1 at /home/simone_a/.julia/juliaup/julia-1.10.0-rc2+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gf.c:2894 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gf.c:3076
jl_apply at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/julia.h:1982 [inlined]
jl_f__call_latest at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/builtins.c:812
#invokelatest#2 at ./essentials.jl:887 [inlined]
invokelatest at ./essentials.jl:884 [inlined]
run_main_repl at ./client.jl:416
exec_options at ./client.jl:333
_start at ./client.jl:552
jfptr__start_82776.1 at /home/simone_a/.julia/juliaup/julia-1.10.0-rc2+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gf.c:2894 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/gf.c:3076
jl_apply at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/julia.h:1982 [inlined]
true_main at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/jlapi.c:582
jl_repl_entrypoint at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/src/jlapi.c:731
main at /cache/build/builder-amdci5-4/julialang/julia-release-1-dot-10/cli/loader_exe.c:58
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4010b8)
Allocations: 232976351 (Pool: 232934559; Big: 41792); GC: 331
Aborted (core dumped)
```
<\details>

**Comment by wsmoses** [comment]
@simsurace can you add Enzyme.API.printall!(true) after using Enzyme and upload the log, for each MWE

**Comment by wsmoses** [comment]
Log from 1.9

[sego.txt](https://github.com/EnzymeAD/Enzyme.jl/files/13664398/sego.txt)

**Comment by simsurace** [comment]
You only need the one from 1.10-0-rc2 now?

**Comment by wsmoses** [comment]
I think this should fix it: https://github.com/EnzymeAD/Enzyme.jl/pull/1195

**Comment by simsurace** [comment]
I tried the main branch (also EnzymeCore#main) with these examples on my machine, but they still crash Julia. How did you make them work?

**Comment by wsmoses** [comment]
Hm the main branch alone should be fine. Can you include the printall log of it now for you?

**Comment by simsurace** [comment]
[log.txt](https://github.com/EnzymeAD/Enzyme.jl/files/13693549/log.txt)

**Comment by wsmoses** [comment]
So from the log, it does have the fix for the segfault I had encountered,
so this seems to have a second issue. I’ll see if I can reproduce it.

**Comment by wsmoses** [comment]
Ok reproduced and hopefully fixed, it was effectively an extension of the previous GC fix for this: https://github.com/EnzymeAD/Enzyme.jl/pull/1198

**Comment by wsmoses** [comment]
Hm something is still going wrong here

**Comment by wsmoses** [comment]
Should be fixed by latest jll bump https://github.com/EnzymeAD/Enzyme.jl/commit/38007ced021e021a25982b7e16a65686ead0dcf3

**Comment by simsurace** [comment]
I can confirm that both examples now work flawlessly. Thanks!
