### ISSUE TITLE
Understanding a huge crash report

### ISSUE THREAD

**Issue by dom-linkevicius** [EnzymeAD/Enzyme.jl#181]
Hello, I am running a custom model involving neural ODEs using Julia 1.7.1 and Enzyme v0.8.1 . My code crashes, I do not understand the reason why (apologies, I am quite new to Julia, I initially posted my query on Julia's discourse page and was directed here), I am getting a huge wall of text and am looking for any pointers to resolve the issue. My model is quite complex so it is difficult to provide a MWE, but hopefully the wall of text is at least somewhat informative. I can try to provide any additional information as requested if it seems like it would be helpful. The crash report can be found [here](https://gist.github.com/dom-linkevicius/391ca694532d2853b881ec6ace999ee6).

**Comment by wsmoses** [comment]
Your error looks quite similar to the one resolved here: https://github.com/wsmoses/Enzyme.jl/pull/184

Once that lands, mind trying it again?

**Comment by dom-linkevicius** [comment]
Tried again with Enzyme v0.8.3, still getting the error. It (at least superficially) seems similar, but the report is longer. [Here](https://gist.github.com/dom-linkevicius/f8d3bdf1545ee935b969ac1bee22628a) is the full crash report after updating Enzyme.

**Comment by vchuravy** [comment]
As a note the relevant bits are almost always towards the end of the dump. The huge wall is necessary to give some context to those messages.

It looks like you are differentiating a Flux model? We are working right now on better support for BLAS operators used in ML, so I would hold off a bit.

Even your complex model might make a decent MWE, but maybe you can narrow it down to which part of the code is giving you problems? We normally comment out bits and pieces. Without an MWE is going to be much harder for us to help

**Comment by wsmoses** [comment]
@dom-linkevicius can you retry on current Enzyme

**Comment by wsmoses** [comment]
@dom-linkevicius closing for now, reopen if the error persists.
