### ISSUE TITLE
Enzyme crash in Lux.jl when using `sin` as activation function

### ISSUE THREAD

**Issue by se-schmitt** [EnzymeAD/Enzyme.jl#2788]
See https://github.com/LuxDL/Lux.jl/issues/1554

MWE:
```julia
using Lux, Random, Optimisers, Enzyme, Printf

cdev = cpu_device()
# xdev = reactant_device()
xdev = cpu_device()
rng = Random.default_rng()
Random.seed!(rng, 0)

X, Y = rand32(rng, 10, 24), rand32(rng, 1, 24)

model = Chain(
    Dense(10, 10, sin),
    Dense(10,  1, sin)
)

ps, st = Lux.setup(rng, model)

ts = Training.TrainState(model, ps, st, AdamW())
(_, loss_j, _, ts) = Training.single_train_step!(AutoEnzyme(), MSELoss(), (X, Y), ts)
```
Julia crash:
```
$ julia mwe.jl 
error: Linking globals named 'julia_sin_25307': symbol multiply defined!
```
Version info:
```
Julia Version 1.11.7
Commit f2b3dbda30a (2025-09-08 12:10 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × AMD Ryzen 5 8540U w/ Radeon 740M Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 12 virtual cores)
```

**Comment by wsmoses** [comment]
@se-schmitt I believe this should be fixed by the rewrite to nested codegen, but reopen if not

**Comment by se-schmitt** [comment]
This is still not working with the same error. Versions:
```
  [7da242da] Enzyme v0.13.172
  [b2108857] Lux v1.31.4
  [f1d291b0] MLUtils v0.4.9
  [3bd65402] Optimisers v0.4.7
  [de0858da] Printf v1.11.0
  [9a3f8284] Random v1.11.0
```
(no permission to reopen)
