### ISSUE TITLE
Incorrect zero primal returned for ComplexF64 inputs

### ISSUE THREAD

**Issue by sethaxen** [EnzymeAD/Enzyme.jl#761]
Now that #758 is fixed, if we use the same example another issues appears, where if the return activity is `Const` and the eltype is `Float64`, the primal value returned is 0.0:

```julia
julia> n = 10;

julia> x, y = randn(ComplexF64, n), randn(ComplexF64, n);

julia> ∂x, ∂y = map(zero, (x, y));

julia> _dot(x, y)
-1.628395690775859 + 1.9870438237721155im

julia> autodiff(ReverseWithPrimal, _dot, Const, Duplicated(x, ∂x), Duplicated(y, ∂y))
((nothing, nothing), 0.0 + 0.0im)
```

Strangely enough, this is fine if we use `ComplexF32`:
```julia
julia> x, y = randn(ComplexF32, n), randn(ComplexF32, n);

julia> ∂x, ∂y = map(zero, (x, y));

julia> _dot(x, y)
-0.91027236f0 + 0.34108874f0im

julia> autodiff(ReverseWithPrimal, _dot, Const, Duplicated(x, ∂x), Duplicated(y, ∂y))
((nothing, nothing), -0.91027236f0 + 0.34108874f0im)
```

**Comment by wsmoses** [comment]
Can you repost the entire reproducer again here for ease?

**Comment by sethaxen** [comment]
Sure, here it is:

```julia
using Enzyme, LinearAlgebra

_scalar_dot(x, y) = conj(x) * y

function _dot(X::StridedArray{T}, Y::StridedArray{T}) where {T<:Union{Real,Complex}}
    return mapreduce(_scalar_dot, +, X, Y)
end

function EnzymeRules.augmented_primal(
    config::EnzymeRules.ConfigWidth{1},
    func::Const{typeof(_dot)},
    RT::Type{<:Union{Const,Active}},
    X::Duplicated{<:StridedArray{T}},
    Y::Duplicated{<:StridedArray{T}},
) where {T<:Union{Real,Complex}}
    r = func.val(X.val, Y.val)
    primal = EnzymeRules.needs_primal(config) ? r : nothing
    shadow = EnzymeRules.needs_shadow(config) ? zero(r) : nothing
    tape = (copy(X.val), copy(Y.val))
    return EnzymeRules.AugmentedReturn(primal, shadow, tape)
end

function EnzymeRules.reverse(
    config::EnzymeRules.ConfigWidth{1},
    ::Const{typeof(_dot)},
    dret::Union{Active,Type{<:Const}},
    tape,
    X::Duplicated{<:StridedArray{T}},
    Y::Duplicated{<:StridedArray{T}},
) where {T<:Union{Real,Complex}}
    if !(dret isa Type{<:Const})
        Xtape, Ytape = tape
        X.dval .+= dret.val .* Ytape
        Y.dval .+= dret.val .* Xtape
    end
    return (nothing, nothing)
end

n = 10
x, y = randn(ComplexF64, n), randn(ComplexF64, n);
∂x, ∂y = map(zero, (x, y));
_dot(x, y)
autodiff(ReverseWithPrimal, _dot, Const, Duplicated(x, ∂x), Duplicated(y, ∂y))

x, y = randn(ComplexF32, n), randn(ComplexF32, n);
∂x, ∂y = map(zero, (x, y));
_dot(x, y)
autodiff(ReverseWithPrimal, _dot, Const, Duplicated(x, ∂x), Duplicated(y, ∂y))
```

**Comment by wsmoses** [comment]
Fixed by https://github.com/EnzymeAD/Enzyme.jl/pull/764

**Comment by sethaxen** [comment]
@wsmoses, I just checked, and on `#main` I still get the same issue (incorrectly returning a primal of 0.0) using the above reproducer.

**Comment by wsmoses** [comment]
Are you sure you're on the right commit? I reproduced locally and resolved via the PR, confirming success.

**Comment by wsmoses** [comment]
Add a PR from main with it as a test, and lets find out?

**Comment by sethaxen** [comment]
> Are you sure you're on the right commit?

Yes, I confirmed.

> Add a PR from main with it as a test, and lets find out?

Done! #769

**Comment by wsmoses** [comment]
Okay this PR should now fix: https://github.com/EnzymeAD/Enzyme.jl/pull/770
